### ISSUE TITLE
Revisit release distribution

### ISSUE THREAD

**Issue by mstimberg** [APGG-Lab/APGG#3]
[Issue opened as part of review openjournals/joss-reviews#4944]

As already mentioned by another reviewer, the release link in the README file links to a non-public website. The tagged releases on the GitHub repository only provide the source archive. Consider either automating the release builds (e.g. via GitHub Actions), or manually upload the archive to a GitHub release.

**Comment by Venku628** [comment]
https://github.com/APGG-Lab/APGG/commit/d8039b043ad8ff2c8d826041f41ab99f7c77f8d9
