### ISSUE TITLE
Should "Visualizer" appear in the class structure?

### ISSUE THREAD

**Issue by mstimberg** [APGG-Lab/APGG#6]
[Issue opened as part of review openjournals/joss-reviews#4944]

The class structure diagram in the wiki and the paper contains the `Visualizer` class, but if I understand correctly, there is no such class in the C++ code, instead visualization is typically done with external tools (e.g. Python scripts). It seems odd to include it in the UML diagram in that case.

**Comment by JDatPNW** [comment]
https://github.com/APGG-Lab/APGG/commit/270ebdc975c4f28150834f3ea635971fd3c54fb2
